# Generated by Django 2.0 on 2018-04-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('fax_number', models.CharField(max_length=30)),
                ('sic_code', models.CharField(max_length=30)),
                ('sic_description', models.CharField(max_length=30)),
                ('webaddress', models.URLField()),
            ],
        ),
    ]
